### ISSUE TITLE
Tag and Category styles does not work for `/tag` and `/category`

### ISSUE THREAD

**Issue by AmirMohamadBabaee** [chen-yingfa/hexo-theme-fengye#3]
Hi, 
First of all, thanks for sharing your work,

I went through your instructions to add tags and categories to my website, but it appears it can use `tag.ejs` and `category.ejs` when rendering the pages. The layout of the page is in post format. Is there any trick or rule of thumb to do so? I will also attach my current setting:

```yml
# _configs.yml
# Header
nav:
  category:
     path: ./category
     icon: mingcute:classify-2-fill
     text: Categories
  tag:
     path: ./tag
     icon: mingcute:tag-fill
     text: Tags
```
